import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const nameRef = useRef<HTMLInputElement>(null);
  const emailRef = useRef<HTMLInputElement>(null);
  const messageRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    // console.log(nameRef.current?.value);

    let data = {
      name: nameRef.current?.value,
      email: emailRef.current?.value,
      message: messageRef.current?.value,
    };

    await fetch("api/contact", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) console.log("メール送信成功");
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5">
        <h2 className="mb-3">Next.js Gmail App</h2>
        <form
          onSubmit={(e: React.FormEvent<HTMLFormElement>) => handleSubmit(e)}
        >
          <div className="mt-3">
            <label htmlFor="name" className="form-label">
              お名前
            </label>
          </div>
          <input type="text" className="fomr-control" id="name" required />
          <div className="mt-3">
            <label htmlFor="email" className="form-label">
              メールアドレス
            </label>
          </div>
          <input
            type="email"
            className="fomr-control"
            id="email"
            required
            ref={emailRef}
          />
          <div className="mt-3 mb-3">
            <label htmlFor="message" className="form-label">
              メッセージ
            </label>
            <textarea
              name="message"
              id="message"
              className="form-control"
              ref={messageRef}
            ></textarea>
          </div>
          <button type="submit" className="btn btn-danger">
            メール送信
          </button>
        </form>
      </div>
    </>
  );
}
